### ISSUE TITLE
Packages missing compared to when running Pipenv outside of container

### ISSUE THREAD

**Issue by themodernlife** [paketo-buildpacks/pip-install#91]
## What happened?

The example repository at https://github.com/themodernlife/buildpack-issue runs fine when run using Homebrew installed toolchain on my Mac, but the docker container built using `pack` fails to run due to missing imports.

* What were you attempting to do?

Here's the main Procfile

```
web: python -c 'from dateutil import tz'
```

And the Pipfile

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pandas = ">=0.25"

[dev-packages]

[requires]
python_version = "3.9"
```

Installing from a new pipenv (installed via Homebrew) from scratch and inspecting the dependencies

```
pipenv  --python 3.9.7
pipenv install 'pandas>=0.25'
pipenv run python -c 'from dateutil import tz'
```

Everything succeeds.  Reverse dependency tree is

```
numpy==1.22.0
  - pandas==1.3.5 [requires: numpy>=1.17.3]
pip==21.3.1
pytz==2021.3
  - pandas==1.3.5 [requires: pytz>=2017.3]
setuptools==60.2.0
six==1.16.0
  - python-dateutil==2.8.2 [requires: six>=1.5]
    - pandas==1.3.5 [requires: python-dateutil>=2.7.3]
wheel==0.37.1
```

But building with `pack build buildpack-issue --buildpack gcr.io/paketo-buildpacks/python --builder `

```
paketobuildpacks/builder:base

base: Pulling from paketobuildpacks/builder
Digest: sha256:870c31cc75ff074deaa32da58a8de150c9ba2cbef8a750dd8f0c6b1fd4aa7aaf
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:59aa1da9db6d979e21721e306b9ce99a7c4e3d1663c4c20f74f9b3876cce5192
Status: Image is up to date for paketobuildpacks/run:base-cnb
latest: Pulling from paketo-buildpacks/python
Digest: sha256:1805b6ff5f2b4ef38b40f132a16f571817d75f448c6a25ec0696bf3c9df230aa
Status: Image is up to date for gcr.io/paketo-buildpacks/python:latest
===> DETECTING
7 of 10 buildpacks participating
paketo-buildpacks/ca-certificates 2.4.2
paketo-buildpacks/cpython         0.7.3
paketo-buildpacks/pip             0.7.0
paketo-buildpacks/pipenv          0.2.1
paketo-buildpacks/pipenv-install  0.2.3
paketo-buildpacks/python-start    0.7.0
paketo-buildpacks/procfile        4.4.1
===> ANALYZING
Restoring metadata for "paketo-buildpacks/ca-certificates:helper" from app image
Restoring metadata for "paketo-buildpacks/cpython:cpython" from app image
Restoring metadata for "paketo-buildpacks/pip:pip" from cache
Restoring metadata for "paketo-buildpacks/pipenv:pipenv" from cache
Restoring metadata for "paketo-buildpacks/pipenv-install:packages" from app image
Restoring metadata for "paketo-buildpacks/pipenv-install:cache" from cache
===> RESTORING
Restoring data for "paketo-buildpacks/cpython:cpython" from cache
Restoring data for "paketo-buildpacks/pip:pip" from cache
Restoring data for "paketo-buildpacks/pipenv:pipenv" from cache
Restoring data for "paketo-buildpacks/pipenv-install:cache" from cache
Restoring data for "paketo-buildpacks/pipenv-install:packages" from cache
===> BUILDING

Paketo CA Certificates Buildpack 2.4.2
  https://github.com/paketo-buildpacks/ca-certificates
  Launch Helper: Reusing cached layer
Paketo CPython Buildpack 0.7.3
  Resolving CPython version
    Candidate version sources (in priority order):
      Pipfile.lock -> "3.9"
                   -> ""
      <unknown>    -> ""

    Selected CPython version (using Pipfile.lock): 3.9.7

  Reusing cached layer /layers/paketo-buildpacks_cpython/cpython

Paketo Pip Buildpack 0.7.0
  Resolving Pip version
    Candidate version sources (in priority order):
       -> ""

    Selected Pip version (using ): 21.3.1

  Reusing cached layer /layers/paketo-buildpacks_pip/pip
Paketo Pipenv Buildpack 0.2.1
  Resolving Pipenv version
    Candidate version sources (in priority order):
       -> ""

    Selected Pipenv version (using ): 2021.5.29

  Reusing cached layer /layers/paketo-buildpacks_pipenv/pipenv
Paketo Pipenv Install Buildpack 0.2.3
  Executing build process
    Running 'pipenv install --deploy'
    Running 'pipenv clean'
  Configuring environment
    PATH           -> "/layers/paketo-buildpacks_pipenv-install/packages/workspace-dqq3IVyd/bin:$PATH"
    PYTHONUSERBASE -> "/layers/paketo-buildpacks_pipenv-install/packages/workspace-dqq3IVyd"

      Completed in 6.033s

Paketo Python Start Buildpack 0.7.0
  Assigning launch process
    web: python

Paketo Procfile Buildpack 4.4.1
  https://github.com/paketo-buildpacks/procfile
  Process types:
    web: python -c 'from dateutil import tz'
===> EXPORTING
Reusing layer 'paketo-buildpacks/ca-certificates:helper'
Adding layer 'paketo-buildpacks/cpython:cpython'
Reusing layer 'paketo-buildpacks/pipenv-install:packages'
Reusing 1/1 app layer(s)
Reusing layer 'launcher'
Reusing layer 'config'
Reusing layer 'process-types'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting default process type 'web'
Saving buildpack-issue...
*** Images (c8ace4a0c91e):
      buildpack-issue
Adding cache layer 'paketo-buildpacks/cpython:cpython'
Adding cache layer 'paketo-buildpacks/pip:pip'
Adding cache layer 'paketo-buildpacks/pipenv:pipenv'
Adding cache layer 'paketo-buildpacks/pipenv-install:cache'
Reusing cache layer 'paketo-buildpacks/pipenv-install:packages'
Successfully built image buildpack-issue
```

Running via `docker run -it buildpack-issue` fails

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/layers/paketo-buildpacks_pipenv-install/packages/workspace-dqq3IVyd/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/layers/paketo-buildpacks_pipenv-install/packages/workspace-dqq3IVyd/lib/python3.9/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

On my Mac, in the virtualenv, I have `six.py`

```
➜  buildpack-issue ls -alh /Users/ihummel/.local/share/virtualenvs/buildpack-issue-yEnhB5G3/lib/python3.9/site-packages 
total 104
drwxr-xr-x  27 ihummel  staff   864B Jan 14 08:55 .
drwxr-xr-x   3 ihummel  staff    96B Jan 14 08:54 ..
drwxr-xr-x   3 ihummel  staff    96B Jan 14 08:54 __pycache__
drwxr-xr-x   4 ihummel  staff   128B Jan 14 08:54 _distutils_hack
-rw-r--r--   1 ihummel  staff    18B Jan 14 08:54 _virtualenv.pth
-rw-r--r--   1 ihummel  staff   5.5K Jan 14 08:54 _virtualenv.py
drwxr-xr-x  14 ihummel  staff   448B Jan 14 08:54 dateutil
-rw-r--r--   1 ihummel  staff   152B Jan 14 08:54 distutils-precedence.pth
drwxr-xr-x  39 ihummel  staff   1.2K Jan 14 08:55 numpy
drwxr-xr-x  10 ihummel  staff   320B Jan 14 08:55 numpy-1.22.0.dist-info
drwxr-xr-x  21 ihummel  staff   672B Jan 14 08:55 pandas
drwxr-xr-x  10 ihummel  staff   320B Jan 14 08:55 pandas-1.3.5.dist-info
drwxr-xr-x   7 ihummel  staff   224B Jan 14 08:54 pip
drwxr-xr-x   9 ihummel  staff   288B Jan 14 08:54 pip-21.3.1.dist-info
-rw-r--r--   1 ihummel  staff     0B Jan 14 08:54 pip-21.3.1.virtualenv
drwxr-xr-x   6 ihummel  staff   192B Jan 14 08:54 pkg_resources
drwxr-xr-x   9 ihummel  staff   288B Jan 14 08:54 python_dateutil-2.8.2.dist-info
drwxr-xr-x  10 ihummel  staff   320B Jan 14 08:54 pytz
drwxr-xr-x   9 ihummel  staff   288B Jan 14 08:54 pytz-2021.3.dist-info
drwxr-xr-x  40 ihummel  staff   1.3K Jan 14 08:54 setuptools
drwxr-xr-x   9 ihummel  staff   288B Jan 14 08:54 setuptools-59.6.0.dist-info
-rw-r--r--   1 ihummel  staff     0B Jan 14 08:54 setuptools-59.6.0.virtualenv
drwxr-xr-x   8 ihummel  staff   256B Jan 14 08:54 six-1.16.0.dist-info
-rw-r--r--   1 ihummel  staff    34K Jan 14 08:54 six.py
drwxr-xr-x  12 ihummel  staff   384B Jan 14 08:54 wheel
drwxr-xr-x   9 ihummel  staff   288B Jan 14 08:54 wheel-0.37.0.dist-info
-rw-r--r--   1 ihummel  staff     0B Jan 14 08:54 wheel-0.37.0.virtualenv
```

`six.py` module is not installed into the container

```
cnb@097fd68eee1c:/workspace$ ls -alh /layers/paketo-buildpacks_pipenv-install/packages/workspace-dqq3IVyd/lib/python3.9/site-packages/
total 92K
drwxr-xr-x 19 cnb cnb 4.0K Jan  1  1980 .
drwxr-xr-x  3 cnb cnb 4.0K Jan  1  1980 ..
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 _distutils_hack
-rw-r--r--  1 cnb cnb   18 Jan  1  1980 _virtualenv.pth
-rw-r--r--  1 cnb cnb 5.6K Jan  1  1980 _virtualenv.py
drwxr-xr-x  6 cnb cnb 4.0K Jan  1  1980 dateutil
-rw-r--r--  1 cnb cnb  151 Jan  1  1980 distutils-precedence.pth
drwxr-xr-x 19 cnb cnb 4.0K Jan  1  1980 numpy
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 numpy-1.22.0.dist-info
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 numpy.libs
drwxr-xr-x 16 cnb cnb 4.0K Jan  1  1980 pandas
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 pandas-1.3.5.dist-info
drwxr-xr-x  4 cnb cnb 4.0K Jan  1  1980 pip
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 pip-21.3.1.dist-info
-rw-r--r--  1 cnb cnb    0 Jan  1  1980 pip-21.3.1.virtualenv
drwxr-xr-x  5 cnb cnb 4.0K Jan  1  1980 pkg_resources
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 python_dateutil-2.8.2.dist-info
drwxr-xr-x  4 cnb cnb 4.0K Jan  1  1980 pytz
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 pytz-2021.3.dist-info
drwxr-xr-x  6 cnb cnb 4.0K Jan  1  1980 setuptools
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 setuptools-60.2.0.dist-info
-rw-r--r--  1 cnb cnb    0 Jan  1  1980 setuptools-60.2.0.virtualenv
drwxr-xr-x  4 cnb cnb 4.0K Jan  1  1980 wheel
drwxr-xr-x  2 cnb cnb 4.0K Jan  1  1980 wheel-0.37.1.dist-info
-rw-r--r--  1 cnb cnb    0 Jan  1  1980 wheel-0.37.1.virtualenv
```

* What did you expect to happen?

The environments should be the same and the container should run.

* What was the actual behavior? Please provide log output, if possible.

Container didn't run

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

```
➜  buildpack-issue git:(main) pack --version                                                                                                              
0.23.0+git-0db2c77.build-3056
```

Installed via Homebrew on macOS 11.6.2

* What buildpacks are you using? Please include versions.

see above

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

Using `paketobuildpacks/builder:base`

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

see above

## Checklist

* [ x] I have included log output.
* [ x] The log output includes an error message.
* [ x] I have included steps for reproduction.

**Comment by themodernlife** [comment]
Will close and reopen under https://github.com/paketo-buildpacks/pipenv-install.  Sorry for the noise!
